### PR TITLE
Avoid errors by quote problems

### PR DESCRIPTION
**Pull request by nocyamribeiro**
PR to solve issue [78](https://github.com/denishpatel/pg-clone-schema/issues/78)
  
I just add a call to quote_ident in every situation to solve this issue. After this, everything works well in my case.

### CODE REVIEW

**Comment by MichaelDBA** [comment]
> I had three consecutive errors related to the quote problem. Here they are:
> 
> 
> ```
> SQL Error [P0001]: ERROR: Action: Tables  Diagnostics: line=SQL statement "ALTER TABLE teste_clone."CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT" ALTER COLUMN FACT_ORDER SET DEFAULT nextval('teste_clone."CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT_FACT_ORDER_seq"'::regclass)"
> PL/pgSQL function clone_schema(text,text,boolean,boolean) line 688 at EXECUTE. 42703. column "fact_order" of relation "CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT" does not exist
>  Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1584 at RAISE
> ```
> 
> 
> ```
> SQL Error [P0001]: ERROR: Action: PRIVS: Sequences  Diagnostics: line=SQL statement "GRANT SELECT ON teste_clone.CUBE_72a2ff79600040f488b43fe7887a6da7_FACT_FACT_ORDER_seq TO "user";"
> PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1488 at EXECUTE. 42P01. relation "teste_clone.cube_72a2ff79600040f488b43fe7887a6da7_fact_fact_order_seq" does not exist
>   Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1584 at RAISE
> ```
> 
> 
> ```
> SQL Error [P0001]: ERROR: Action: PRIVS: Tables  Diagnostics: line=SQL statement "GRANT DELETE ON TABLE teste_clone.CUBE_6c1b118be1df454e8b1770822d5cbe45_FACT TO user;"
> PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1563 at EXECUTE. 42P01. relation "teste_clone.cube_6c1b118be1df454e8b1770822d5cbe45_fact" does not exist
>   Where: PL/pgSQL function clone_schema(text,text,boolean,boolean) line 1584 at RAISE
> ```
> 
> I just add a call to quote_ident in every situation to solve this issue. After this, everything works well in my case.

Hi @nocyamribeiro, Would you mind creating an issue first before you create a pull request?  We prefer to track changes through issues.

**Comment by nocyamribeiro** [comment]
> 

Ok. I'll create a issue with this problem. Thanks!

**Comment by nocyamribeiro** [comment]
> > 
> 
> Ok. I'll create a issue with this problem. Thanks!

@MichaelDBA I created issue [78](https://github.com/denishpatel/pg-clone-schema/issues/78).

**Comment by MichaelDBA** [comment]
Per the related issue, I made many other changes in this regard including yours so your changes can be seen in the latest code.

**Pull request closed without merging**
